# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: maru2
    main: ./cmd/maru2
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: maru2

  - id: maru2-publish
    main: ./cmd/maru2-publish
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w"
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: maru2-publish

archives:
  - formats: [tar.gz]
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

brews:
  - name: maru2
    repository:
      owner: defenseunicorns
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      branch: "{{ .ProjectName }}-{{ .Tag }}"
      pull_request:
        enabled: true
        base:
          branch: main
          owner: defenseunicorns
          name: homebrew-tap
    commit_msg_template: "build(release): upgrade {{ .ProjectName }} to {{ .Tag }}"
    homepage: "https://github.com/defenseunicorns/maru2"
    description: "A simple task runner"
    post_install: |
      generate_completions_from_executable(bin/"maru2", "completion")
      generate_completions_from_executable(bin/"maru2-publish", "completion")

  # NOTE: We are using .Version instead of .Tag because homebrew has weird semver parsing rules and won't be able to
  #       install versioned releases that has a `v` character before the version number.
  - name: "maru2@{{ .Version }}"
    repository:
      owner: defenseunicorns
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
      branch: "{{ .ProjectName }}-{{ .Tag }}"
      pull_request:
        enabled: true
        base:
          branch: main
          owner: defenseunicorns
          name: homebrew-tap
    commit_msg_template: "build(release): {{ .ProjectName }}@{{ .Tag }}"
    homepage: "https://github.com/defenseunicorns/maru2"
    description: "A simple task runner"
    post_install: |
      generate_completions_from_executable(bin/"maru2@{{ .Version }}", "completion")
      generate_completions_from_executable(bin/"maru2-publish@{{ .Version }}", "completion")

changelog:
  disable: true

checksum:
  name_template: "checksums.txt"

release:
  mode: keep-existing
