name: 🐛 Bug Report
description: File a bug report to help us improve maru2
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please search existing issues before creating a new one.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened instead?
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. See error
      render: markdown
    validations:
      required: true

  - type: textarea
    id: task-file
    attributes:
      label: Task file (if applicable)
      description: Please provide the task file content that reproduces the issue
      render: yaml
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: maru2 Version
      description: What version of maru2 are you running?
      placeholder: "v0.1.2 (or commit hash if using main)"
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: go-version
    attributes:
      label: Go Version
      description: What version of Go are you using? (if building from source)
      placeholder: "go version go1.24.3 linux/amd64"
    validations:
      required: false

  - type: textarea
    id: logs
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, including screenshots if applicable.
    validations:
      required: false
