blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/defenseunicorns/maru2/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔒 Security Issues
    url: https://github.com/defenseunicorns/maru2/security/advisories/new
    about: Report security vulnerabilities privately
