# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025-Present Defense Unicorns

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    # milestoned is added here as a workaround for release-please not triggering PR workflows (PRs should be added to a milestone to trigger the workflow).
    types: [milestoned, opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.24.x
          cache-dependency-path: |
            go.sum
            go.mod
      - run: make
      - run: go test -race -covermode=atomic -coverprofile=coverage.out -failfast -timeout 3m ./...
      # - uses: codecov/codecov-action@v5.4.0
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      - run: |
          go test -fuzz=FuzzTaskNamePattern -fuzztime=15s
          go test -fuzz=FuzzEnvVariablePattern -fuzztime=15s

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: 1.24.x
          cache-dependency-path: |
            go.sum
            go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest

  # fossa-scan:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: fossas/fossa-action@v1.5.0
  #       with:
  #         api-key: ${{ secrets.FOSSA_API_KEY }}
