# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025-Present Defense Unicorns

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
    types: [milestoned, opened, edited, synchronize]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: go-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: build & test
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - run: make
      - run: |
          if ! git diff --exit-code maru2.schema.json; then
            echo "maru2.schema.json is dirty. Please run 'make' and commit the changes"
            exit 1
          fi
          if ! git diff --exit-code schema/v0/schema.json; then
            echo "schema/v0/schema.json is dirty. Please run 'make' and commit the changes"
            exit 1
          fi
      - run: |
          go test -race -covermode=atomic -coverprofile=coverage.out -failfast -timeout 3m ./...
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          go tool cover -func=coverage.out | sort -k3 -n
      - run: |
          go test ./schema/v0 -run=^$ -fuzz=FuzzTaskNamePattern -fuzztime=15s
          go test ./schema/v0 -run=^$ -fuzz=FuzzEnvVariablePattern -fuzztime=15s

  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9 # v8.0.0
        with:
          version: latest
